import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instant Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-1 lg:grid-cols-4 ">
          <div className="col-span-1">
            <Sidebar />
          </div>
          <div className="col-span-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
